name = "ParticleHolography"
uuid = "b8f7f481-73e0-42c6-b6bd-c66d3b4942cc"
authors = ["Dai Nakai <dainakai1031@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
